export const crops = ['Wheat', 'Corn', 'Soy', 'Rice', 'Beans', 'Cotton'];

export const location: Record<string, string[]>[] = [
  {
    SP: [
      'São Paulo',
      'Campinas',
      'São Bernardo do Campo',
      'Santo André',
      'Osasco',
      'Guarulhos',
      'Sorocaba',
      'Ribeirão Preto',
      'São José dos Campos',
      'Santos',
      'Jundiaí',
      'Bauru',
      'Piracicaba',
      'Mogi das Cruzes',
      'Franca',
      'Carapicuíba',
      'Marília',
      'Presidente Prudente',
      'Araçatuba',
      'Barueri',
    ],
  },
  {
    MG: [
      'Belo Horizonte',
      'Uberlândia',
      'Contagem',
      'Juiz de Fora',
      'Betim',
      'Montes Claros',
      'Ribeirão das Neves',
      'Uberaba',
      'Governador Valadares',
      'Ipatinga',
      'Sete Lagoas',
      'Divinópolis',
      'Santa Luzia',
      'Ibirité',
      'Poços de Caldas',
      'Patos de Minas',
      'Pouso Alegre',
      'Teófilo Otoni',
      'Passos',
      'Araxá',
    ],
  },
  {
    MT: [
      'Cuiabá',
      'Várzea Grande',
      'Rondonópolis',
      'Sinop',
      'Tangará da Serra',
      'Sorriso',
      'Lucas do Rio Verde',
      'Cáceres',
      'Primavera do Leste',
      'Barra do Garças',
      'Alta Floresta',
      'Campo Verde',
      'Pontes e Lacerda',
      'Alta Floresta',
      'Peixoto de Azevedo',
      'Diamantino',
      'Guarantã do Norte',
      'Juína',
      'Nova Mutum',
      'Jaciara',
    ],
  },
  {
    MS: [
      'Campo Grande',
      'Dourados',
      'Três Lagoas',
      'Corumbá',
      'Ponta Porã',
      'Naviraí',
      'Nova Andradina',
      'Amambai',
      'Maracaju',
      'Sidrolândia',
      'Aquidauana',
      'Paranaíba',
      'Rio Brilhante',
      'Coxim',
      'São Gabriel do Oeste',
      'Cassilândia',
      'Itaporã',
      'Anastácio',
      'Bonito',
      'Jardim',
    ],
  },
  {
    GO: [
      'Goiânia',
      'Anápolis',
      'Aparecida de Goiânia',
      'Rio Verde',
      'Luziânia',
      'Águas Lindas de Goiás',
      'Senador Canedo',
      'Trindade',
      'Formosa',
      'Catalão',
      'Itumbiara',
      'Novo Gama',
      'Jataí',
      'Planaltina',
      'Ceres',
      'Cristalina',
      'Inhumas',
      'Mineiros',
      'Itaberaí',
      'Jaraguá',
    ],
  },
  {
    TO: [
      'Palmas',
      'Araguaína',
      'Gurupi',
      'Porto Nacional',
      'Paraíso do Tocantins',
      'Colinas do Tocantins',
      'Guaraí',
      'Dianópolis',
      'Tocantinópolis',
      'Miracema do Tocantins',
      'Araguatins',
      'Xambioá',
      'Wanderlândia',
      'Augustinópolis',
      'Formoso do Araguaia',
      'Pium',
      'Taguatinga',
      'Natividade',
      'Alvorada',
      'Miranorte',
    ],
  },
  {
    PA: [
      'Belém',
      'Ananindeua',
      'Santarém',
      'Marabá',
      'Castanhal',
      'Parauapebas',
      'Abaetetuba',
      'Cametá',
      'Bragança',
      'Marituba',
      'Itaituba',
      'Redenção',
      'Altamira',
      'Barcarena',
      'Tucuruí',
      'Tailândia',
      'Capanema',
      'Paragominas',
      'Moju',
      'Salinópolis',
    ],
  },
  {
    AM: [
      'Manaus',
      'Parintins',
      'Itacoatiara',
      'Manacapuru',
      'Coari',
      'Tefé',
      'Tabatinga',
      'Maués',
      'Humaitá',
      'Lábrea',
      'Manicoré',
      'São Gabriel da Cachoeira',
      'Eirunepé',
      'Borba',
      'Iranduba',
      'Autazes',
      'Careiro',
      'Nova Olinda do Norte',
      'Presidente Figueiredo',
      'Barreirinha',
    ],
  },
];
